{% set name = "sqlalchemy-searchable" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy_searchable-{{ version }}.tar.gz
  sha256: d4869f9c295c6f17a2c4491976ceeb2b4a0b56f89b18c3881753d768eb467906

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - sqlalchemy-utils >=0.40.0
    - sqlalchemy >=1.4

test:
  imports:
    - sqlalchemy_searchable
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Provides fulltext search capabilities for declarative SQLAlchemy models.
  home: https://github.com/falcony-io/sqlalchemy-searchable
  doc_url: https://sqlalchemy-searchable.readthedocs.io/en/latest/
  dev_url: https://github.com/falcony-io/sqlalchemy-searchable
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
