{% set name = "sqlalchemy-searchable" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy_searchable-{{ version }}.tar.gz
  sha256: 89d120ed1a752d22e32b3f028f62cae571241ccce081df8d8a42e1fa9a53da93

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - sqlalchemy-utils >=0.40.0
    - sqlalchemy >=1.4

test:
  imports:
    - sqlalchemy_searchable
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Provides fulltext search capabilities for declarative SQLAlchemy models.
  home: https://github.com/falcony-io/sqlalchemy-searchable
  doc_url: https://sqlalchemy-searchable.readthedocs.io/en/latest/
  dev_url: https://github.com/falcony-io/sqlalchemy-searchable
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
